server:
  port: 9000

spring:
  application: API-gateway
  cloud:
    gateway:
      routes:
        - id: bookservice
          url: http://localhost:9001
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter
        - id: employeeservice
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthFilter
        - id: borrowservice
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/borrows/**
          filters:
            - AuthFilter
      default-filters:
        - DecupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
