server:
  port: 9001

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3307/book
    username: root
    password: 2292892000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka